### ISSUE TITLE
As a developer, I want vendored dependency management, so generated code compiles correctly.

### ISSUE THREAD

**Issue by MatthewHartstonge** [MatthewHartstonge/truss#2]
Look at generating a [glide](http://glide.sh) `yaml` file in the root of the `--svcout` folder for Go dependency management. Glide use is fairly common nowadays and truss seems to generate code for a version of `go-kit` that hasn't been released. 
It generates code for a commit of go-kit in between `v0.3.0` and `v0.4.0`

**Comment by MatthewHartstonge** [comment]
@pauln has started looking into this.

**Comment by zaquestion** [comment]
Hey Matthew, for what its worth we talked about doing this in early truss development. Nowadays dep would be the preferred tool if this feature was to be adopted. https://github.com/golang/dep

**Comment by MatthewHartstonge** [comment]
Hey @zaquestion love the idea of `go dep` but currently the main issue I have with it is that it won't be introduced into the tool chain until Go 1.10. (6-7 months away).

What are you thoughts on the following:
 - keep current implementation, but add glide gen via a flag
 - Maintain glide as a second class citizen due to it's wide adoption via a switch like `--glide-deps`

In other thoughts, it looks like `go dep` will slurp in `glide.yaml` files on init so we could use `glide.yml` until `go dep` is introduced to Go 1.10 then transition.

**Comment by adamryman** [comment]
We use `govendor` currently. https://github.com/kardianos/govendor

We found glide very hard to work with for a variety of reasons. The lead of go at Uber also agreeded with us that glide has issues. Particularly with updating a single dependency. 
 
While `dep` will not be introduced to the actual go tool chain till 1.10, it is still usable independently.

**Comment by MatthewHartstonge** [comment]
Don't really know why I started issues here - going to migrate/reference the issues in truss.. 
I started using it as a point for visibility between @pauln and myself as we tackled the issues together.
